import moment from "moment";

const products = [
  {
    id: 1,
    name: "Bocker",
    details:
      "Beautiful white-washed wood display book. It features black printed French titles to add a touch of sophistication and intelligence, complete with PVC green leaves on top for some extra flair. This will be a timeless home decor item that will go well with almost any livingroom, bedroom, or study.",
    category: "decor",
    type: "table decor",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 4.75,
      height: 7.125,
      depth: 3,
    },
    image: "/products/bocker.jpg",
    price: 60.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.2,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 2,
    name: "Andrakoppen",
    details:
      "This beautifully crafted mug will be your favorite for coffee. The wonderful design with plain texture and shine adds a hand-made feel. ",
    category: "kitchen",
    type: "cup",
    sale: false,
    dimensions: {
      width: 5.24,
      height: 4.33,
      depth: 5.24,
    },
    image: "/products/andrakoppen.jpg",
    price: 19.99,
    reviews: [
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 3,
    name: "Kopp",
    details:
      "Enjoy coffee with this elegant coffee mug.  Perfect for coffee lovers.",
    category: "kitchen",
    type: "cup",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 4.75,
      height: 7.125,
      depth: 3,
    },
    image: "/products/kopp.jpg",
    price: 60.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 4,
    name: "Bekvam",
    details:
      "A beautiful addition to your guest room – or even the master suite – this platform bed features a simple, versatile silhouette. ",
    category: "bedroom",
    type: "bed",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 37,
      height: 74,
      depth: 10,
    },
    image: "/products/bekvam.jpg",
    price: 529.99,
    reviews: [
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 5,
    name: "Bruntsate",
    details:
      "This sofa can fit perfectly with a contemporary look, scandinavian style, or a more boho-looking living space. ",
    category: "livingroom",
    type: "sofa",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 71.3,
      height: 29.9,
      depth: 37.8,
    },
    image: "/products/bruntsate.jpg",
    price: 1220.99,
    reviews: [
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 6,
    name: "Entill",
    details:
      "Simple with just the right amount of scandinavian flair, this dining set is the best addition to a small condo and cozy living situations.",
    category: "diningroom",
    type: "dining set",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 30,
      height: 30,
      depth: 47,
    },
    image: "/products/entill.jpg",
    price: 669.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 7,
    name: "Fluffig",
    details:
      "This beautiful tufted armchair adds comfort and elegance to your home. It uses teddy fabric, a fusion of boho style and modern life.",
    category: "livingroom",
    type: "chair",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 25.3,
      height: 32.28,
      depth: 31,
    },
    image: "/products/fluffig.jpg",
    price: 359.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 8,
    name: "Grejer",
    details:
      "This 6 piece bath set creates a timeless elegance of a 5-star Scandinavation spa of long-lasting quality for years to come.",
    category: "bathroom",
    type: "bath accessories",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 4.75,
      height: 2.125,
      depth: 9,
    },
    image: "/products/grejer.jpg",
    price: 46.99,
    reviews: [
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 9,
    name: "Haftigt",
    details:
      "Relax in comfort with this plush sofa. This exemplary furniture of scandinavian style works well in converted lofts and modern condos alike. ",
    category: "livingroom",
    type: "sofa",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 24,
      height: 18,
      depth: 48,
    },
    image: "/products/haftigt.jpg",
    price: 1499.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 10,
    name: "Hylla",
    details:
      "This beautiful handmade floating shelf sports a rectangular silhouette and boasts a natural pine wood finish. It is sure to catch the eye in any ensemble, and provides plenty of room to perch books, photos, plants, and more up top.",
    category: "bedroom",
    type: "shelf",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 44,
      height: 5,
      depth: 8,
    },
    image: "/products/hylla.jpg",
    price: 54.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
    ],
  },
  {
    id: 11,
    name: "Kantig",
    details:
      "Looking for a modern and sleek decoration to hang on your wall? This frame is the perfect choice for your home and office décor. Has a keyhole on the back for easy hanging on your wall.",
    category: "decor",
    type: "wall decor",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 16,
      height: 20,
      depth: 1.5,
    },
    image: "/products/kantig.jpg",
    price: 32.99,
    reviews: [
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 12,
    name: "Sev",
    details:
      "Handmade all-natural scented candle. It is made of soy and palm 100% vegetable oil wax. It will fill any room with a heavenly romantic scent of flowers and plants.",
    category: "decor",
    type: "tabletop decor",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 4,
      height: 6,
      depth: 4,
    },
    image: "/products/sev.jpg",
    price: 19.99,
    reviews: [
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 13,
    name: "Malning",
    details:
      "This beautiful watercolor picture fills in the blanks on an empty wall, and brings the wall to life. It has a premium hand-wrapped Giclée canvas, 100% made in China and created to last.",
    category: "decor",
    type: "wall art",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 14,
      height: 20,
      depth: 1.5,
    },
    image: "/products/malning.jpg",
    price: 36.99,
    reviews: [
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 14,
    name: "Matplats",
    details:
      "This simple dining set with mid-century modern style will complete your space.  In a space-saving design, you and your friends can enjoy game nights and socialize around this dining table.",
    category: "diningroom",
    type: "dining set",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 47.5,
      height: 30,
      depth: 27.5,
    },
    image: "/products/matplats.jpg",
    price: 589.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 15,
    name: "Mertabell",
    details:
      "Full of modern style, the table features a black glass surface, while the seats are upholstered in black velvet fabric with stitch details and tapered legs. This five-piece set is a perfect way to round out your home with on-trend dining.",
    category: "diningroom",
    type: "dining set",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 30,
      height: 48.5,
      depth: 27.5,
    },
    image: "/products/mertabell.jpg",
    price: 699.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 16,
    name: "Nattduksbord",
    details:
      "With a clean, minimalist silhouette and square-tube, it's the essence of modern scandinavian style. ",
    category: "bedroom",
    type: "nightstand",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 20.5,
      height: 5.8,
      depth: 14,
    },
    image: "/products/nattduksbord.jpg",
    price: 169.99,
    reviews: [
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
    ],
  },
  {
    id: 17,
    name: "Rundkruka",
    details:
      "This stunning ceramic bud vase can be used on its own for a beautiful statement piece or works well with flower and faux florals.",
    category: "decor",
    type: "tabletop decor",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 3,
      height: 5.7,
      depth: 3,
    },
    image: "/products/rundkruka.jpg",
    price: 16.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
    ],
  },
  {
    id: 18,
    name: "Forsmadlig",
    details:
      "Great for adding a decorative touch to any room's decor. Wonderful accent piece for coffee tables or side tables.",
    category: "decor",
    type: "tabletop decor",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 4,
      height: 12,
      depth: 4,
    },
    image: "/products/forsmadlig.jpg",
    price: 36.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 19,
    name: "Annan",
    details:
      "Show off your blooms to their best by pairing them with this vase, a timeless pick suited for classic and modern spaces. ",
    category: "decor",
    type: "tabletop decor",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 6,
      height: 4.5,
      depth: 4.5,
    },
    image: "/products/annan.jpg",
    price: 42.99,
    reviews: [
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 20,
    name: "Sidobord",
    details:
      "Whether set beside your sofa in the livingroom or pulled up to your bedside for a charming nightstand, this end table is an excellent addition to any ensemble.",
    category: "livingroom",
    type: "end table",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 22,
      height: 23,
      depth: 13,
    },
    image: "/products/sidobord.jpg",
    price: 129.99,
    reviews: [
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 21,
    name: "Sittplatser",
    details:
      "Elegant lines and contemporary design make the sofa a timeless piece for livingrooms and seating areas.",
    category: "livingroom",
    type: "sofa",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 63.77,
      height: 30.7,
      depth: 31.49,
    },
    image: "/products/sittplatser.jpg",
    price: 1059.99,
    reviews: [
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 22,
    name: "Sittpuff",
    details:
      "Perfect for using as an extra table or offering a spare seat at your next soiree, this posh pouf brings both fashion and function to your space.",
    category: "livingroom",
    type: "chair",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 20,
      height: 14,
      depth: 20,
    },
    image: "/products/sittpuff.jpg",
    price: 124.99,
    reviews: [
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 23,
    name: "Skap",
    details:
      "Beautiful craftsmanship and intricate detailing, with durable splayed wood legs, beveled top, and sleek handles to finish. This beautiful sideboard offers ample space for tucking away dishes, tablecloths, and dinnerware to host ultimate dinner parties.",
    category: "diningroom",
    type: "sideboard",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 62.99,
      height: 33.07,
      depth: 14.96,
    },
    image: "/products/skap.jpg",
    price: 509.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 24,
    name: "Skon",
    details:
      "This elegant mid-Century modern sofa is the perfect way to add both style and comfort to your home.",
    category: "livingroom",
    type: "sofa",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 85,
      height: 34,
      depth: 31,
    },
    image: "/products/skon.jpg",
    price: 1359.99,
    reviews: [
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 25,
    name: "Slumpmassig",
    details:
      "Add a sense of decoration to your livingroom or bedroom, or use the mirror to create the illusion of more space in the home.",
    category: "decor",
    type: "mirror",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 16,
      height: 16,
      depth: 1.6,
    },
    image: "/products/slumpmassig.jpg",
    price: 116.99,
    reviews: [
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 26,
    name: "Spegel",
    details:
      "From offering a glimpse of your reflection to opening up a smaller space, mirrors are a versatile addition to any arrangement in your home. Plus, they double as decorative accents!",
    category: "decor",
    type: "mirror",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 20,
      height: 30,
      depth: 2,
    },
    image: "/products/spegel-gold.jpg",
    price: 98.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a wall.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 27,
    name: "Svartkruka",
    details:
      "This vase, skillfully crafted from ceramic, is a beautiful and unique addition to your space that looks great by itself or when paired with other vases that compliment it.",
    category: "decor",
    type: "tabletop decor",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 4.53,
      height: 11.02,
      depth: 4.53,
    },
    image: "/products/svartkruka.jpg",
    price: 56.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
    ],
  },
  {
    id: 28,
    name: "Tallrik",
    details:
      "Bring fashionable elegance to your home with this set of 4 plates. Every piece has a soft matte finish that brings a scandinavian touch to your dish collection.",
    category: "kitchen",
    bestseller: false,
    sale: false,
    dimensions: {
      width: 8,
      height: 8,
      depth: 1.5,
    },
    image: "/products/tallrik-beige.jpg",
    price: 26.99,
    reviews: [
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 29,
    name: "Tickande",
    details:
      "This eye-catching wall clock instantly elevates your favourite aesthetic. Its round silhouette blends effortlessly into both casual or formal spaces, while its clean profile adds sophistication to your decor.",
    category: "wall decor",
    type: "clock",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 9.5,
      height: 9.5,
      depth: 1.25,
    },
    image: "/products/tickande.jpg",
    price: 42.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
    ],
  },
  {
    id: 30,
    name: "Trosta",
    details:
      "A fresh, clean console table that is versatile in any space. Roomy drawer to store remotes, glasses, or even table linens.",
    category: "livingroom",
    type: "table",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 36,
      height: 32,
      depth: 14,
    },
    image: "/products/trosta.jpg",
    price: 229.99,
    reviews: [
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 31,
    name: "Vadsomhelst",
    details:
      "A stunning alternative to traditional dining sets. The kitchen chairs are designed with padded faux leather cushions and the bottom legs are equipped with anti-scratches and anti-noise pads to protect your floor.",
    category: "dining table",
    type: "dining set",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 35.4,
      height: 35.4,
      depth: 29.5,
    },
    image: "/products/vadsomhelst.jpg",
    price: 259.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
    ],
  },
  {
    id: 32,
    name: "Vaxtbehallare",
    details:
      "This wood flower vase set is made of natural Paulownia wood. This is an ideal selection of vintage room decor adding a modern scandinavian touch to your home.",
    category: "decor",
    type: "tabletop decor",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 3.3,
      height: 7.5,
      depth: 3.1,
    },
    image: "/products/vaxtbehallare.jpg",
    price: 59.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 33,
    name: "Vaxtbricka",
    details:
      "Instantly create an eye-catching display of elegance on your coffee table or window sill with this table vase. This set arrives with a wooden tray for your vase to sit to create a beautiful cohesive display.",
    category: "decor",
    type: "tabletop decor",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 4.75,
      height: 7.125,
      depth: 3,
    },
    image: "/products/vaxtbricka.jpg",
    price: 60.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.5,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 34,
    name: "Vaxtkruka",
    details:
      "Displayed in your dining or livingroom, entryways or hallways, this vase set is sure to bring charm and joy to any space. The neutral tones will work with any color palette.",
    category: "kitchen",
    type: "dining set",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 5.45,
      height: 12,
      depth: 5.45,
    },
    image: "/products/vaxtkruka.jpg",
    price: 32.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Colleen",
        location: "Antioch, TN",
        date: moment("2022-01-11"),
        entry: "Nice but smaller than I expected.",
        rating: 4.1,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 35,
    name: "Vitbord",
    details:
      "Mix a dash of mid-century modern flair into your entertainment ensemble with this dining set. A two-toned white and brown finish outfits this set for crisp contrast, while still ensuring it’s neutral enough to complement any colour palette.",
    category: "diningroom",
    type: "dining set",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 30,
      height: 32,
      depth: 30,
    },
    image: "/products/vitbord.jpg",
    price: 460.99,
    reviews: [
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 36,
    name: "Vitstol",
    details:
      "Putting an elegant style on simplicity, this armchair features luxurious velvet fabric, and a button-tufted seat back for added flair.",
    category: "livingroom",
    type: "chair",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 28.3,
      height: 33.4,
      depth: 26.3,
    },
    image: "/products/vitstol.jpg",
    price: 312.99,
    reviews: [
      {
        username: "Vicki",
        location: "Vancouver, WA",
        date: moment("2021-08-23"),
        entry: "Absolutely Perfect.",
        rating: 4.5,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
];

export default products;
