import moment from "moment";
import sale from "./components/Sale";

const products = [
  {
    id: 1,
    name: "Bocker",
    details:
      "Beautiful white-washed wood display book. It features black printed French titles to add a touch of sophistication and intelligence, complete with PVC green leaves on top for some extra flair. This will be a timeless home decor item that will go well with almost any livingroom, bedroom, or study.",
    category: "decor",
    itemsSold: 231,
    dateAdded: moment("2021-01-20"),
    productId: "price_1KMkgIBrSUNo10EJAYD6hDsi",
    type: "table decor",
    sale: false,
    bestseller: false,
    dimensions: {
      width: 4.75,
      height: 7.125,
      depth: 3,
    },
    image: "/assets/bocker.jpg",
    price: 60.99,
    reviews: [
      {
        username: "Angelica",
        location: "Garland, TX",
        date: moment("2022-01-20"),
        entry: "Wish it was bigger but overall nice piece.",
        rating: 4.5,
      },
      {
        username: "Kristi",
        location: "Leawood, KS",
        date: moment("2021-11-28"),
        entry: "Great little accent to a corner.",
        rating: 4.2,
      },
      {
        username: "Kathy",
        location: "Salem, OR",
        date: moment("2021-10-16"),
        entry: "This was a gift.",
        rating: 5.0,
      },
      {
        username: "Chrisharo",
        location: "Dallas, TX",
        date: moment("2021-05-01"),
        entry: "Exactly as shown on the site.",
        rating: 4.5,
      },
    ],
  },
  {
    id: 2,
    name: "Andrakoppen",
    details:
      "This beautifully crafted mug will be your favorite for coffee. The wonderful design with plain texture and shine adds a hand-made feel. ",
    category: "kitchen",
    type: "cup",
    sale: false,
    productId: "price_1KMkgqBrSUNo10EJcVu8W0Hy",
    itemsSold: 131,
    dateAdded: moment("2020-04-20"),
    dimensions: {
      width: 5.24,
      height: 4.33,
      depth: 5.24,
    },
    image: "/assets/andrakoppen.jpg",
    price: 19.99,
  },
  {
    id: 3,
    name: "Kopp",
    details:
      "Enjoy coffee with this elegant coffee mug.  Perfect for coffee lovers.",
    category: "kitchen",
    type: "cup",
    sale: false,
    itemsSold: 410,
    productId: "price_1KMkhaBrSUNo10EJbKwh9klt",
    dateAdded: moment("2021-07-10"),
    bestseller: false,
    dimensions: {
      width: 4.75,
      height: 7.125,
      depth: 3,
    },
    image: "/assets/kopp.jpg",
    price: 60.99,
  },
  {
    id: 4,
    name: "Bekvam",
    details:
      "A beautiful addition to your guest room – or even the master suite – this platform bed features a simple, versatile silhouette. ",
    category: "bedroom",
    type: "bed",
    sale: false,
    itemsSold: 31,
    productId: "price_1KMki2BrSUNo10EJq0MgBFW5",
    dateAdded: moment("2021-04-22"),
    bestseller: false,
    dimensions: {
      width: 37,
      height: 74,
      depth: 10,
    },
    image: "/assets/bekvam.jpg",
    price: 529.99,
  },
  {
    id: 5,
    name: "Bruntsate",
    details:
      "This sofa can fit perfectly with a contemporary look, scandinavian style, or a more boho-looking living space. ",
    category: "livingroom",
    type: "sofa",
    itemsSold: 121,
    dateAdded: moment("2021-07-28"),
    sale: true,
    productId: "price_1KMkjNBrSUNo10EJ9LfG1E4p",
    bestseller: false,
    dimensions: {
      width: 71.3,
      height: 29.9,
      depth: 37.8,
    },
    image: "/assets/bruntsate.jpg",
    price: 1220.99,
  },
  {
    id: 6,
    name: "Entill",
    details:
      "Simple with just the right amount of scandinavian flair, this dining set is the best addition to a small condo and cozy living situations.",
    category: "diningroom",
    type: "dining set",
    sale: false,
    productId: "price_1KMkjqBrSUNo10EJvrUeJMnV",
    itemsSold: 61,
    dateAdded: moment("2021-05-10"),
    bestseller: false,
    dimensions: {
      width: 30,
      height: 30,
      depth: 47,
    },
    image: "/assets/entill.jpg",
    price: 669.99,
  },
  {
    id: 7,
    name: "Fluffig",
    details:
      "This beautiful tufted armchair adds comfort and elegance to your home. It uses teddy fabric, a fusion of boho style and modern life.",
    category: "livingroom",
    type: "chair",
    sale: false,
    productId: "price_1KMkkfBrSUNo10EJv9kfq0Ug",
    itemsSold: 171,
    dateAdded: moment("2021-09-21"),
    bestseller: false,
    dimensions: {
      width: 25.3,
      height: 32.28,
      depth: 31,
    },
    image: "/assets/fluffig.jpg",
    price: 359.99,
  },
  {
    id: 8,
    name: "Grejer",
    details:
      "This 6 piece bath set creates a timeless elegance of a 5-star Scandinavation spa of long-lasting quality for years to come.",
    category: "bathroom",
    type: "bath accessories",
    sale: false,
    itemsSold: 178,
    productId: "price_1KMkl5BrSUNo10EJxQ3njMHD",
    dateAdded: moment("2021-04-16"),
    bestseller: false,
    dimensions: {
      width: 4.75,
      height: 2.125,
      depth: 9,
    },
    image: "/assets/grejer.jpg",
    price: 46.99,
  },
  {
    id: 9,
    name: "Haftigt",
    details:
      "Relax in comfort with this plush sofa. This exemplary furniture of scandinavian style works well in converted lofts and modern condos alike. ",
    category: "livingroom",
    type: "sofa",
    sale: false,
    itemsSold: 58,
    productId: "price_1KMklWBrSUNo10EJtHlAsU4Y",
    dateAdded: moment("2021-07-06"),
    bestseller: false,
    dimensions: {
      width: 24,
      height: 18,
      depth: 48,
    },
    image: "/assets/haftigt.jpg",
    price: 1499.99,
  },
  {
    id: 10,
    name: "Hylla",
    details:
      "This beautiful handmade floating shelf sports a rectangular silhouette and boasts a natural pine wood finish. It is sure to catch the eye in any ensemble, and provides plenty of room to perch books, photos, plants, and more up top.",
    category: "bedroom",
    type: "shelf",
    sale: true,
    itemsSold: 91,
    productId: "price_1KMkm4BrSUNo10EJe4bxIVXq",
    dateAdded: moment("2021-01-15"),
    bestseller: false,
    dimensions: {
      width: 44,
      height: 5,
      depth: 8,
    },
    image: "/assets/hylla.jpg",
    price: 54.99,
  },
  {
    id: 11,
    name: "Kantig",
    details:
      "Looking for a modern and sleek decoration to hang on your wall? This frame is the perfect choice for your home and office décor. Has a keyhole on the back for easy hanging on your wall.",
    category: "decor",
    type: "wall decor",
    sale: false,
    itemsSold: 207,
    productId: "price_1KMkmPBrSUNo10EJuShWJ3yy",
    dateAdded: moment("2021-09-01"),
    bestseller: false,
    dimensions: {
      width: 16,
      height: 20,
      depth: 1.5,
    },
    image: "/assets/kantig.jpg",
    price: 32.99,
  },
  {
    id: 12,
    name: "Sev",
    details:
      "Handmade all-natural scented candle. It is made of soy and palm 100% vegetable oil wax. It will fill any room with a heavenly romantic scent of flowers and plants.",
    category: "decor",
    type: "tabletop decor",
    sale: false,
    itemsSold: 319,
    productId: "price_1KMkmfBrSUNo10EJJkE2QjdC",
    dateAdded: moment("2021-02-09"),
    bestseller: false,
    dimensions: {
      width: 4,
      height: 6,
      depth: 4,
    },
    image: "/assets/sev.jpg",
    price: 19.99,
  },
  {
    id: 13,
    name: "Malning",
    details:
      "This beautiful watercolor picture fills in the blanks on an empty wall, and brings the wall to life. It has a premium hand-wrapped Giclée canvas, 100% made in China and created to last.",
    category: "decor",
    type: "wall art",
    productId: "price_1KMknABrSUNo10EJ4nlQUZ1H",
    sale: true,
    itemsSold: 284,
    dateAdded: moment("2021-04-06"),
    bestseller: false,
    dimensions: {
      width: 14,
      height: 20,
      depth: 1.5,
    },
    image: "/assets/malning.jpg",
    price: 36.99,
  },
  {
    id: 14,
    name: "Matplats",
    details:
      "This simple dining set with mid-century modern style will complete your space.  In a space-saving design, you and your friends can enjoy game nights and socialize around this dining table.",
    category: "diningroom",
    type: "dining set",
    productId: "price_1KMknXBrSUNo10EJmGH7SqvQ",
    sale: false,
    itemsSold: 52,
    dateAdded: moment("2021-08-09"),
    bestseller: false,
    dimensions: {
      width: 47.5,
      height: 30,
      depth: 27.5,
    },
    image: "/assets/matplats.jpg",
    price: 589.99,
  },
  {
    id: 15,
    name: "Mertabell",
    details:
      "Full of modern style, the table features a black glass surface, while the seats are upholstered in black velvet fabric with stitch details and tapered legs. This five-piece set is a perfect way to round out your home with on-trend dining.",
    category: "diningroom",
    productId: "price_1KMknwBrSUNo10EJXbZBOCZm",
    type: "dining set",
    sale: false,
    itemsSold: 78,
    dateAdded: moment("2021-08-04"),
    bestseller: false,
    dimensions: {
      width: 30,
      height: 48.5,
      depth: 27.5,
    },
    image: "/assets/mertabell.jpg",
    price: 699.99,
  },
  {
    id: 16,
    name: "Nattduksbord",
    details:
      "With a clean, minimalist silhouette and square-tube, it's the essence of modern scandinavian style. ",
    category: "bedroom",
    type: "nightstand",
    productId: "price_1KMkoLBrSUNo10EJKK4zDzz5",
    sale: false,
    itemsSold: 94,
    dateAdded: moment("2021-06-30"),
    bestseller: false,
    dimensions: {
      width: 20.5,
      height: 5.8,
      depth: 14,
    },
    image: "/assets/nattduksbord.jpg",
    price: 169.99,
  },
  {
    id: 17,
    name: "Rundkruka",
    details:
      "This stunning ceramic bud vase can be used on its own for a beautiful statement piece or works well with flower and faux florals.",
    category: "decor",
    type: "tabletop decor",
    productId: "price_1KMkovBrSUNo10EJ6UDJK5Ej",
    sale: true,
    itemsSold: 161,
    dateAdded: moment("2021-05-11"),
    bestseller: false,
    dimensions: {
      width: 3,
      height: 5.7,
      depth: 3,
    },
    image: "/assets/rundkruka.jpg",
    price: 16.99,
  },
  {
    id: 18,
    name: "Forsmadlig",
    details:
      "Great for adding a decorative touch to any room's decor. Wonderful accent piece for coffee tables or side tables.",
    category: "decor",
    type: "tabletop decor",
    productId: "price_1KMkpGBrSUNo10EJy6zvjizl",
    sale: false,
    itemsSold: 94,
    dateAdded: moment("2021-02-17"),
    bestseller: false,
    dimensions: {
      width: 4,
      height: 12,
      depth: 4,
    },
    image: "/assets/forsmadlig.jpg",
    price: 36.99,
  },
  {
    id: 19,
    name: "Annan",
    details:
      "Show off your blooms to their best by pairing them with this vase, a timeless pick suited for classic and modern spaces. ",
    category: "decor",
    type: "tabletop decor",
    productId: "price_1KMkpYBrSUNo10EJ16EX9KU0",
    sale: false,
    itemsSold: 420,
    dateAdded: moment("2021-03-18"),
    bestseller: false,
    dimensions: {
      width: 6,
      height: 4.5,
      depth: 4.5,
    },
    image: "/assets/annan.jpg",
    price: 42.99,
  },
  {
    id: 20,
    name: "Sidobord",
    details:
      "Whether set beside your sofa in the livingroom or pulled up to your bedside for a charming nightstand, this end table is an excellent addition to any ensemble.",
    category: "livingroom",
    type: "end table",
    productId: "price_1KMkq7BrSUNo10EJYyFMT6ZM",
    sale: true,
    itemsSold: 76,
    dateAdded: moment("2021-02-18"),
    bestseller: false,
    dimensions: {
      width: 22,
      height: 23,
      depth: 13,
    },
    image: "/assets/sidobord.jpg",
    price: 129.99,
  },
  {
    id: 21,
    name: "Sittplatser",
    details:
      "Elegant lines and contemporary design make the sofa a timeless piece for livingrooms and seating areas.",
    category: "livingroom",
    type: "sofa",
    productId: "price_1KMkqcBrSUNo10EJuUjqrdov",
    sale: false,
    itemsSold: 10,
    dateAdded: moment("2022-01-18"),
    bestseller: false,
    dimensions: {
      width: 63.77,
      height: 30.7,
      depth: 31.49,
    },
    image: "/assets/sittplatser.jpg",
    price: 1059.99,
  },
  {
    id: 22,
    name: "Sittpuff",
    details:
      "Perfect for using as an extra table or offering a spare seat at your next soiree, this posh pouf brings both fashion and function to your space.",
    category: "livingroom",
    type: "chair",
    sale: true,
    itemsSold: 109,
    productId: "price_1KMkr2BrSUNo10EJT12B65Ek",
    dateAdded: moment("2021-04-08"),
    bestseller: false,
    dimensions: {
      width: 20,
      height: 14,
      depth: 20,
    },
    image: "/assets/sittpuff.jpg",
    price: 124.99,
  },
  {
    id: 23,
    name: "Skap",
    details:
      "Beautiful craftsmanship and intricate detailing, with durable splayed wood legs, beveled top, and sleek handles to finish. This beautiful sideboard offers ample space for tucking away dishes, tablecloths, and dinnerware to host ultimate dinner parties.",
    category: "diningroom",
    type: "sideboard",
    itemsSold: 420,
    sale: false,
    productId: "price_1KMkrIBrSUNo10EJq4joFDqZ",
    itemsSold: 114,
    dateAdded: moment("2021-08-08"),
    bestseller: false,
    dimensions: {
      width: 62.99,
      height: 33.07,
      depth: 14.96,
    },
    image: "/assets/skap.jpg",
    price: 509.99,
  },
  {
    id: 24,
    name: "Skon",
    details:
      "This elegant mid-Century modern sofa is the perfect way to add both style and comfort to your home.",
    category: "livingroom",
    type: "sofa",
    sale: false,
    productId: "price_1KMkrgBrSUNo10EJoYINwUR0",
    itemsSold: 69,
    dateAdded: moment("2021-03-19"),
    bestseller: false,
    dimensions: {
      width: 85,
      height: 34,
      depth: 31,
    },
    image: "/assets/skon.jpg",
    price: 1359.99,
  },
  {
    id: 25,
    name: "Slumpmassig",
    details:
      "Add a sense of decoration to your livingroom or bedroom, or use the mirror to create the illusion of more space in the home.",
    category: "decor",
    type: "mirror",
    productId: "price_1KMks3BrSUNo10EJzFxATSuW",
    sale: false,
    itemsSold: 239,
    dateAdded: moment("2021-06-12"),
    bestseller: false,
    dimensions: {
      width: 16,
      height: 16,
      depth: 1.6,
    },
    image: "/assets/slumpmassig.jpg",
    price: 116.99,
  },
  {
    id: 26,
    name: "Spegel",
    details:
      "From offering a glimpse of your reflection to opening up a smaller space, mirrors are a versatile addition to any arrangement in your home. Plus, they double as decorative accents!",
    category: "decor",
    type: "mirror",
    sale: true,
    itemsSold: 99,
    productId: "price_1KMksoBrSUNo10EJVPsWhfzC",
    dateAdded: moment("2021-07-22"),
    bestseller: false,
    dimensions: {
      width: 20,
      height: 30,
      depth: 2,
    },
    image: "/assets/spegel-gold.jpg",
    price: 98.99,
  },
  {
    id: 27,
    name: "Svartkruka",
    details:
      "This vase, skillfully crafted from ceramic, is a beautiful and unique addition to your space that looks great by itself or when paired with other vases that compliment it.",
    category: "decor",
    type: "tabletop decor",
    sale: false,
    itemsSold: 472,
    productId: "price_1KMktJBrSUNo10EJCYfIxOGU",
    dateAdded: moment("2021-01-28"),
    bestseller: false,
    dimensions: {
      width: 4.53,
      height: 11.02,
      depth: 4.53,
    },
    image: "/assets/svartkruka.jpg",
    price: 56.99,
  },
  {
    id: 28,
    name: "Tallrik",
    details:
      "Bring fashionable elegance to your home with this set of 4 plates. Every piece has a soft matte finish that brings a scandinavian touch to your dish collection.",
    category: "kitchen",
    bestseller: false,
    sale: false,
    itemsSold: 509,
    productId: "price_1KMktfBrSUNo10EJGJCkTFsJ",
    dateAdded: moment("2021-02-17"),
    dimensions: {
      width: 8,
      height: 8,
      depth: 1.5,
    },
    image: "/assets/tallrik-beige.jpg",
    price: 26.99,
  },
  {
    id: 29,
    name: "Tickande",
    details:
      "This eye-catching wall clock instantly elevates your favourite aesthetic. Its round silhouette blends effortlessly into both casual or formal spaces, while its clean profile adds sophistication to your decor.",
    category: "wall decor",
    type: "clock",
    sale: false,
    itemsSold: 389,
    productId: "price_1KMktxBrSUNo10EJgEZFTFBx",
    dateAdded: moment("2021-08-16"),
    bestseller: false,
    dimensions: {
      width: 9.5,
      height: 9.5,
      depth: 1.25,
    },
    image: "/assets/tickande.jpg",
    price: 42.99,
  },
  {
    id: 30,
    name: "Trosta",
    details:
      "A fresh, clean console table that is versatile in any space. Roomy drawer to store remotes, glasses, or even table linens.",
    category: "livingroom",
    type: "table",
    sale: false,
    itemsSold: 89,
    productId: "price_1KMkuFBrSUNo10EJfz79f78u",
    dateAdded: moment("2021-09-13"),
    bestseller: false,
    dimensions: {
      width: 36,
      height: 32,
      depth: 14,
    },
    image: "/assets/trosta.jpg",
    price: 229.99,
  },
  {
    id: 31,
    name: "Vadsomhelst",
    details:
      "A stunning alternative to traditional dining sets. The kitchen chairs are designed with padded faux leather cushions and the bottom legs are equipped with anti-scratches and anti-noise pads to protect your floor.",
    category: "dining table",
    type: "dining set",
    sale: false,
    itemsSold: 64,
    productId: "price_1KMkuZBrSUNo10EJl7AAzcvg",
    dateAdded: moment("2021-11-28"),
    bestseller: false,
    dimensions: {
      width: 35.4,
      height: 35.4,
      depth: 29.5,
    },
    image: "/assets/vadsomhelst.jpg",
    price: 259.99,
  },
  {
    id: 32,
    name: "Vaxtbehallare",
    details:
      "This wood flower vase set is made of natural Paulownia wood. This is an ideal selection of vintage room decor adding a modern scandinavian touch to your home.",
    category: "decor",
    type: "tabletop decor",
    sale: false,
    itemsSold: 169,
    productId: "price_1KMkuyBrSUNo10EJZkyjDq6F",
    dateAdded: moment("2021-12-12"),
    bestseller: false,
    dimensions: {
      width: 3.3,
      height: 7.5,
      depth: 3.1,
    },
    image: "/assets/vaxtbehallare.jpg",
    price: 59.99,
  },
  {
    id: 33,
    name: "Vaxtbricka",
    details:
      "Instantly create an eye-catching display of elegance on your coffee table or window sill with this table vase. This set arrives with a wooden tray for your vase to sit to create a beautiful cohesive display.",
    category: "decor",
    productId: "price_1KMkvNBrSUNo10EJOEBJ8RYi",
    type: "tabletop decor",
    sale: false,
    itemsSold: 299,
    dateAdded: moment("2021-01-03"),
    bestseller: false,
    dimensions: {
      width: 4.75,
      height: 7.125,
      depth: 3,
    },
    image: "/assets/vaxtbricka.jpg",
    price: 60.99,
  },
  {
    id: 34,
    name: "Vaxtkruka",
    details:
      "Displayed in your dining or livingroom, entryways or hallways, this vase set is sure to bring charm and joy to any space. The neutral tones will work with any color palette.",
    category: "decor",
    productId: "price_1KMkvlBrSUNo10EJs0uIgeac",
    type: "tabletop decor",
    sale: false,
    itemsSold: 29,
    dateAdded: moment("2022-01-12"),
    bestseller: false,
    dimensions: {
      width: 5.45,
      height: 12,
      depth: 5.45,
    },
    image: "/assets/vaxtkruka.jpg",
    price: 32.99,
  },
  {
    id: 35,
    name: "Vitbord",
    details:
      "Mix a dash of mid-century modern flair into your entertainment ensemble with this dining set. A two-toned white and brown finish outfits this set for crisp contrast, while still ensuring it’s neutral enough to complement any colour palette.",
    category: "diningroom",
    type: "dining set",
    productId: "price_1KMkw6BrSUNo10EJ09Jn0BWB",
    sale: false,
    itemsSold: 65,
    dateAdded: moment("2021-08-10"),
    bestseller: false,
    dimensions: {
      width: 30,
      height: 32,
      depth: 30,
    },
    image: "/assets/vitbord.jpg",
    price: 460.99,
  },
  {
    id: 36,
    name: "Vitstol",
    details:
      "Putting an elegant style on simplicity, this armchair features luxurious velvet fabric, and a button-tufted seat back for added flair.",
    category: "livingroom",
    type: "chair",
    sale: false,
    itemsSold: 103,
    productId: "price_1KMkwUBrSUNo10EJZmImUg9P",
    dateAdded: moment("2021-07-29"),
    bestseller: false,
    dimensions: {
      width: 28.3,
      height: 33.4,
      depth: 26.3,
    },
    image: "/assets/vitstol.jpg",
    price: 312.99,
  },
];

export default products;
